image: Visual Studio 2017

clone_folder: '%USERPROFILE%\go\src\github.com\topfreegames\libpitaya'

environment:
  nodejs_version: "Current"

build:
  verbosity: detailed

configuration: Release

platform: x64

artifacts:
  - path: build\*.dll
    name: Dlls

  - path: build\*.lib
    name: Libs

install:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

before_build:
  - cd %USERPROFILE%\go\src\github.com\topfreegames\libpitaya
  - mkdir build && cd build
  - cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=Release -DPITAYA_LIB_TYPE=SHARED ..

build_script:
  - cmake --build .

after_build:
  - dir

deploy:
  description: 'Release'
  provider: GitHub
  draft: true
  auth_token:
    secure: "zZylescCEij0QU44MySw8xIQgBjmRJfD/p/42ddQQoxLoFzC4TP+kkZm3ywsrKo6"
  artifact: /.*\.dll|.*\.lib/
  on:
    appveyor_repo_tag: true

