image: Visual Studio 2015

clone_folder: '%USERPROFILE%\go\src\github.com\topfreegames\libpitaya'

environment:
  nodejs_version: "Current"

build:
  verbosity: detailed

configuration: Release

platform: x64

artifacts:
  - path: build\out\Release_x64\output\*.dll
    name: Dlls

  - path: build\out\Release_x64\output\*.lib
    name: Libs

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  #- call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

  ############################################################################
  # Install Ninja
  ############################################################################
  - choco install ninja

  ############################################################################
  # Install GYP
  ############################################################################
  - mkdir C:\projects\deps
  - cd C:\projects\deps
  - git clone https://chromium.googlesource.com/external/gyp
  - cd gyp
  - python setup.py install

  ############################################################################
  # Install Go dependencies
  ############################################################################
  - cd %USERPROFILE%\go\src\github.com\topfreegames
  - git clone https://github.com/leohahn/pitaya
  - cd %USERPROFILE%\go\src\github.com\topfreegames\libpitaya
  - cd pitaya-servers\json-server
  - go get
  - cd ..\protobuf-server
  - go get

before_build:
  - cd %USERPROFILE%\go\src\github.com\topfreegames\libpitaya
  - gyp --depth=. pitaya.gyp -f ninja --generator-output=build -Duse_sys_openssl=true -Dbuild_type=Release -Dbuild_for_windows=true -Dtarget_arch=x64 -Dpitaya_target=pitaya-windows

build_script:
  - cd build\out\Release_x64
  - ninja
  - cd %USERPROFILE%\go\src\github.com\topfreegames\libpitaya
  - python run-tests.py 

after_build:
  - dir output

deploy:
  description: 'Release'
  provider: GitHub
  draft: true
  auth_token:
    secure: "zZylescCEij0QU44MySw8xIQgBjmRJfD/p/42ddQQoxLoFzC4TP+kkZm3ywsrKo6"
  artifact: /.*\.dll|.*\.lib/
  on:
    appveyor_repo_tag: true

